services:

  db:
    image: postgres
    container_name: postgres-nest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "king-martinien"
      POSTGRES_PASSWORD: example